## This function contains two functions that generate and store the inverse 
## of a matrix in a cache for later use without requiring recalculation.

## The first function initialzes the matrix and inverse matrix which are    
## populated and stored based on user input of the starting matrix and the 
## result of inversion obtained from the second function. The result and 
## initial input are stored in a list.

makeCacheMatrix <- function(x = matrix()) {
        m <- NULL
        set <- function(y) {
                x <<- y
                m <<- NULL
        }
        get <- function() x
        setinverse <- function(inverse) m <<- inverse
        getinverse <- function() m
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}


## The second function takes the list generated by the first function and if 
## an inverse is present, it retrieves it with a message indicating that it 
## is doing so. Otherwise the function inverses the matrix for the first time, 
## stores it back in the list for later use ("caches" it), and returns the 
## result to the console. Repeated use of the second function on the same
## matrix (via the list created earlier) will pull the result from the cache
## thus avoiding recalculation of the inverse.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        m <- x$getinverse()
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- solve(data, ...)
        x$setinverse(m)
        m
}
