## These functions generate and store the inverse of a matrix 
## in a cache for later use without requiring recalculation

## Initialze matrix and inverse matrix for input from cacheSolve
## and store it in a list

makeCacheMatrix <- function(x = matrix()) {
        m <- NULL
        set <- function(y) {
                x <<- y
                m <<- NULL
        }
        get <- function() x
        setinverse <- function(inverse) m <<- inverse
        getinverse <- function() m
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}


## Takes list generated by makeCacheMatrix as input and checks it 
## for inverse. If the inverse has already been generated, then
## it pulls it, otherwise the function inverses the matrix for the
## for the first time and stores it back in the list for later use.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        m <- x$getinverse()
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- solve(data, ...)
        x$setinverse(m)
        m
}
